### PR TITLE
Asgmt3 580611044

### PR DESCRIPTION
**Pull request by peech44**
I hate git in android studio!!! it make me waste time so much

### CODE REVIEW

**Comment by navadon** [comment]
Sorry to hear that you hate it. However, you did a good job (except you forgot to put "Back" button as required in the assignment).

**Comment by peech44** [comment]
oh no i forgot its , Thank you for that I think only next botton

**Comment by peech44** [comment]
I uploaded its. can you see its? I not sure about new version is uploaded.

**Comment by peech44** [comment]
Or close this pull request and create new pull request

**Comment by navadon** [comment]
Got it. Checked.

**Pull request closed without merging**
